let conversions = {
    replacements: [
        ["flip a coin", "roll a quarter"],
        ["search for a better life", "buscar una vida mejor"],
        ["^((?!up a ))gondola","up a gondola"],
        [" a ", " an "],
        ["^((?!joey ))electron", "joey electron"],
        ["the best song", ["unravel", "russian national anthem", "H3H3 theme", "anything from the NieR: Automata soundtrack"]],
        ["the worst song", ["re re english version"]],
        ["2b", "shiri"],
        ["a2", "shiri"],
        ["engineer", "IF YOU'RE SURE"],
        ["trump", "drumpf"],
        ["easy", ["not rocket surgery", "simple economics", "wining as cloud in smash", "your mom"]],
        ["supreme", "sheep"],
        ["sombra", "up a gondola"],
        ["mercy", "R2"],
        ["kevin zhou", "ricegum"],
        ["God", ["El Duque", "Ryan Jizmus", "Cork", "ya boi Joey Electron","lucio"]],
        ["lawyer", "Feit's Mom in the past life"],

        ["better life", "vida mejor"],
        ["rick and morty", ["Rich and Marvin", "quantum physics", "theoretical physics"]],
        ["albert einstein", ["someone who understands the subtle humor of rick and morty", "10th grade delmonaco", "a 12 year old after watching death note"]],
        ["theoretical physics", "rick and morty"],
        ["^((?!aka )|(?!neutron from ))jimmy neutron", "jonny quasar aka jimmy neutron from jimmy neutron: boy genius"],
        ["berke", "beaver"],
        ["lucio", "jamaica"],
        ["international baccalaureate", "some welsh organization that makes explicit/demonstrates and destroys lives, hopes, and will to live to a large extent in a formal or informal manner"],
        ["entonces", "entonthes"],
        [" so ", " entonthes "],
        ["galicia", "galithia"],
        ["mike delmonaco", "moke_delmonaco"],
        ["edge", "Neneguy_"],
        ["edgy", "Neneguy_"],
        ["ryan jaunzemis", "pickup god"],
        ["junkrat", "needs a buff like seriously"],
        ["jeff kaplan", "junkrat main"],
        ["dictator", "grant weisberg"],
        ["^((?!FAT ))grav", "FAT grav"],
        ["screen door", "broke af"],
        ["if bobby would've would've would've done that", "yes"],
        ["bobby", ["bobu", "squid", "squiddy", "young squid on the tracks", "a sixth grader", "trash at little mac", "trash at mei", "trash at zarya"]],
        ["universe", ["a pringle chip", "wuju", "left skate"]],
        ["where is my phone?", "my dog has it"],
        ["richard", "yoooooo riiiiiich"],
        ["my baby boy", "Jack Randall"],
        ["afterthought", "Jack Randall"],
        ["kailash","in"],
        ["winston", "wiiinstoon"],
        ["soap", "Ryan Jaunzemis"],
        ["fake", ["AidanG73_deleting_this_soon"]],
        ["diabetes", "diabetus"],
        ["bro", "vro"],
        ["dead", ["you are already", "joe's sister jokes", "vital emotion's future", "me I wish"]],
        ["slick", "10th grade jdraz after getting a haircut"],
        ["grab", "Eubihn's only move in smash"],
        ["cloud", "OP"],
        ["never sleep", "Feit's brother"],
        ["the best game", ["No Man's Sky", "not sonic", "overwatch but only after junkrat was buffed", "some dumb mobile game aidan plays"]],
        ["shit", ["mobile games", "you at smash", "bobby's mei and zarya", "literally every mobile game except hearthstone"]],
        ["bop", "greninja teleport"],
        ["lesbian", "sneeze"],
        [" if ", " iuf "],
        ["never", ["when bobby will get his pc", "when Feit will be open minded", "when aidan will have an identity", "when Jack/Feit will change his mind","when Feit's mom was wrong(she was a lawyer in the past life you know)","when vital emotion will be successful"]],
        ["what men want",["cloutonium","kevin's famouts chili","more proofs","more rich and marvin"]],
        ["drugs","poppy seeds"],
        ["dollar","clout token"],
        ["plutonium","cloutonium"],
        ["blizzard","don don fujisou"],
        ["hanzo","ganzo"],
        ["kissanime","weeb shit"],
        ["tokyo ghoul","best opening NA"],
        ["fullmetal alchemist: brotherhood","fullmetal alchemist...fullmetal alchemist"],
        ["naruto","too long for bobby"],
        ["attack on titan","a naruto filler"],
        ["spoiler","eubihn"],
        ["korean","chinese"],
        ["korea","china"],
        ["not here","jim's rundown"],
        ["returned","sent it bac"],
        ["returns","sends it bac"],
        ["return","send it bac"],
        ["linguini","gabagool"]
    ]
};
