let conversions = {
    replacements: [
        ["flip a coin", "roll a quarter"],
        ["search for a better life", "buscar una vida mejor"],
        ["^((?!up a ))gondola","up a gondola"],
        [" a ", " an "],
        ["^((?!joey ))electron", "joey electron"],
        ["the best song", ["unravel", "russian national anthem", "H3H3 theme", "anything from the NieR: Automata soundtrack"]],
        ["the worst song", ["re re english version"]],
        ["2b", "shiri"],
        ["a2", "shiri"],
        ["engineer", "IF YOU'RE SURE"],
        ["trump", "drumpf"],
        ["easy", ["not rocket surgery", "simple economics", "wining as cloud in smash", "your mom"]],
        ["supreme", "sheep"],
        ["cancer", ["gan", "toby", "dps instalocks", "Rich and Marvin", "the right skate", "people who don't understand why communism is the best economy", "supreme", "starting an entire convorsation just to say a subreddit", "english versions of anime openings", "To be fair, you have to have a very high IQ to understand Rick and Morty. The humour is extremely subtle, and without a solid grasp of theoretical physics most of the jokes will go over a typical viewer’s head. There’s also Rick’s nihilistic outlook, which is deftly woven into his characterisation- his personal philosophy draws heavily from Narodnaya Volya literature, for instance. The fans understand this stuff; they have the intellectual capacity to truly appreciate the depths of these jokes, to realise that they’re not just funny- they say something deep about LIFE. As a consequence people who dislike Rick & Morty truly ARE idiots- of course they wouldn’t appreciate, for instance, the humour in Rick’s existential catchphrase “Wubba Lubba Dub Dub,” which itself is a cryptic reference to Turgenev’s Russian epic Fathers and Sons. I’m smirking right now just imagining one of those addlepated simpletons scratching their heads in confusion as Dan Harmon’s genius wit unfolds itself on their television screens. What fools.. how I pity them. And yes, by the way, i DO have a Rick & Morty tattoo. And no, you cannot see it. It’s for the ladies’ eyes only- and even then they have to demonstrate that they’re within 5 IQ points of my own (preferably lower) beforehand. Nothin personnel kid"]],
        ["boobs", "dekapai"],
        ["sombra", "up a gondola"],
        ["tree fiddy", "dekapai"],
        ["350", "dekapai"],
        ["mercy", ["dekapai","R2"]],
        ["kevin zhou", "ricegum"],
        ["God", ["El Duque", "Ryan Jizmus", "Cork", "ya boi Joey Electron","lucio"]],
        ["lawyer", "Feit's Mom in the past life"],

        ["better life", "vida mejor"],
        ["rick and morty", ["Rich and Marvin", "quantum physics", "theoretical physics"]],
        ["albert einstein", ["someone who understands the subtle humor of rick and morty", "10th grade delmonaco", "a 12 year old after watching death note"]],
        ["theoretical physics", "rick and morty"],
        ["^((?!aka )|(?!neutron from ))jimmy neutron", "jonny quasar aka jimmy neutron from jimmy neutron: boy genius"],
        ["berke", "beaver"],
        ["lucio", "jamaica"],
        ["international baccalaureate", "some welsh organization that makes explicit/demonstrates and destroys lives, hopes, and will to live to a large extent in a formal or informal manner"],
        ["entonces", "entonthes"],
        [" so ", " entonthes "],
        ["galicia", "galithia"],
        ["mike delmonaco", "moke_delmonaco"],
        ["edge", "Neneguy_"],
        ["edgy", "Neneguy_"],
        ["ryan jaunzemis", "pickup god"],
        ["junkrat", "needs a buff like seriously"],
        ["jeff kaplan", "junkrat main"],
        ["dictator", "grant weisberg"],
        ["^((?!FAT ))grav", "FAT grav"],
        ["nazi", "Lauren Maline"],
        ["screen door", "broke af"],
        ["if bobby would've would've would've done that", "yes"],
        ["bobby", ["bobu", "squid", "squiddy", "squiddy penis", "young squid on the tracks", "a sixth grader", "trash at little mac", "trash at mei", "trash at zarya"]],
        ["aunt jemima", "ms. bryan"],
        ["universe", ["a pringle chip", "wuju", "left skate"]],
        ["nice", "somebody's bitch"],
        ["pornhub","overwatchhentai"],
        ["hentai haven","hey feit"],
        ["russo", "that's it I'm getting PornHub"],
        ["youtube", "kyle russo's source of porn"],
        ["where is my phone?", "my dog has it"],
        ["richard", "yoooooo riiiiiich"],
        ["my baby boy", "Jack Randall"],
        ["afterthought", "Jack Randall"],
        ["katy", "unfinessable girl"],
        ["kailash","in"],
        ["winston", "wiiinstoon"],
        ["soap", "Ryan Jaunzemis"],
        ["fake", ["AidanG73_deleting_this_soon"]],
        ["idiot", ["Howard Fucking Zinn", "vital emotion", "feit", "AidanG73_deleting_this_soon", "apple users"]],
        ["jew", "feit"],
        ["diabetes", "diabetus"],
        ["bro", "vro"],
        ["dead", ["you are already", "joe's sister jokes", "vital emotion's future", "me I wish"]],
        ["lights", ["shiri", "not dekapai @feit"]],
        ["slick", "10th grade jdraz after getting a haircut"],
        ["grab", "Eubihn's only move in smash"],
        ["cloud", "OP"],
        ["never sleep", "Feit's brother"],
        ["the best game", ["No Man's Sky", "not sonic", "overwatch but only after junkrat was buffed", "some dumb mobile game aidan plays"]],
        ["shit", ["mobile games", "you at smash", "bobby's mei and zarya", "literally every mobile game except hearthstone", "vital emotion's value as a person"]],
        ["bop", "greninja teleport"],
        ["lesbian", "sneeze"],
        [" if ", " iuf "],
        ["^((?!fucking ))gay", ["justin simonetti", "you", "fucking gay"]],
        ["never", ["when bobby will get his pc", "when Feit will not be overweight", "when Feit will be open minded", "when aidan will have an identity", "when Jack/Feit will change his mind","when Feit's mom was wrong(she was a lawyer in the past life you know)","when vital emotion will be successful"]],
        ["what men want",["cloutonium","kevin's famouts chili","dekapai","more proofs","more rich and marvin","foot pics for 500"]],
        ["good deal","foot pics for 500"],
        ["drugs","poppy seeds"],
        ["dollar","clout token"],
        ["plutonium","cloutonium"],
        ["danny","chin dimple"],
        ["blizzard","don don fujisou"],
        ["hanzo","ganzo"],
        ["kissanime","weeb shit"],
        ["tokyo ghoul","best opening NA"],
        ["fullmetal alchemist: brotherhood","fullmetal alchemist...fullmetal alchemist"],
        ["naruto","too long for bobby"],
        ["attack on titan","a naruto filler"],
        ["spoiler","eubihn"],
        ["korean","chinese"],
        ["korea","china"],
        ["catalonia","nice try bucko"],
        ["not here","jim's rundown"],
        ["returned","sent it bac"],
        ["returns","sends it bac"],
        ["return","send it bac"],
        ["linguini","gabagool"]
    ]
};
